# -*- coding: utf-8 -*-
"""Practica01.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aSljuBB6WI3ND5xE8_PQpYv8zaSYqEXt

Ejercicio 01:
Introduccion a Numpy: Biblioteca fundam. para la manipulacion de arrays y op. matem. en Python
"""

import numpy as np
#crear un array numpy
array=np.array([1,2,3,4,5])
#realizar operaciones basicas
suma=np.sum(array)
media=np.mean(array)
print ("La suma es:",suma)
print ("La media es:",media)

"""Ejercicio: Cargar y visualizar un conjunto de datos con pandas y matplotlib"""

import pandas as pd
import matplotlib.pyplot as plt

# Cargar un conjunto de datos 'iris'
iris = pd.read_csv('https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data', header=None, names=['sepal_length', 'sepal_width', 'petal_length', 'petal_width', 'class'])

# Mostrar las primeras filas del dataset
print(iris.head())

# Visualizar la distribución de las longitudes de los pétalos
plt.hist(iris['petal_length'], bins=20, color='blue', edgecolor='black')
plt.title('Distribución de la Longitud de los Pétalos')
plt.xlabel('Longitud del Pétalo')
plt.ylabel('Frecuencia')

# Ajustar el diseño y mostrar el gráfico
plt.tight_layout()
plt.show()

#

